project:
  type: website
  output-dir: docs
  resources:
    - data_graph.ttl
    - data_graph.json

website:
  title: "SEC Subsidiary Knowledge Graph"
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - href: ontology.qmd
        text: Ontology Explorer


format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
